import type {ReactNode,ButtonHTMLAttributes,InputHTMLAttributes} from 'react';
import {X} from 'lucide-react';
export function Card({children,className=''}:{children:ReactNode,className?:string}){return <div className={`rounded-2xl border border-slate-200 bg-white shadow-sm ${className}`}>{children}</div>}
export function Button({children,variant='primary',className='',...p}:{children:ReactNode;variant?:'primary'|'secondary'|'danger'|'ghost';className?:string}&ButtonHTMLAttributes<HTMLButtonElement>){const v={primary:'bg-teal-700 text-white hover:bg-teal-800',secondary:'bg-white text-slate-700 border border-slate-200 hover:bg-slate-50',danger:'bg-rose-600 text-white hover:bg-rose-700',ghost:'text-slate-600 hover:bg-slate-100'}[variant];return <button {...p} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50 ${v} ${className}`}>{children}</button>}
export function Input({className='',...p}:InputHTMLAttributes<HTMLInputElement>){return <input {...p} className={`w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100 ${className}`}/>}
export function Select({className='',children,...p}:React.SelectHTMLAttributes<HTMLSelectElement>){return <select {...p} className={`w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-teal-500 ${className}`}>{children}</select>}
export function StatusBadge({status}:{status:string}){const c=status==='Done'||status==='In Stock'?'bg-emerald-50 text-emerald-700':status==='Low Stock'||status==='Ready'?'bg-amber-50 text-amber-700':status==='Out of Stock'||status==='Canceled'?'bg-rose-50 text-rose-700':'bg-slate-100 text-slate-600';return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${c}`}>{status}</span>}
export function Modal({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b border-slate-200 bg-white px-6 py-4"><h2 className="text-lg font-bold text-slate-900">{title}</h2><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X size={20}/></button></div><div className="p-6">{children}</div></div></div>}
export function Toast({message,onClose}:{message:string;onClose:()=>void}){return <div className="fixed bottom-5 right-5 z-[60] flex max-w-sm items-center gap-3 rounded-xl bg-slate-900 px-4 py-3 text-sm font-medium text-white shadow-xl"><span>{message}</span><button onClick={onClose}>×</button></div>}
export function PageHeader({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-slate-950">{title}</h1>{description&&<p className="mt-1 text-sm text-slate-500">{description}</p>}</div>{action}</div>}
export function EmptyState({title,text}:{title:string;text:string}){return <div className="py-12 text-center"><div className="mx-auto mb-3 h-10 w-10 rounded-full bg-slate-100"/><h3 className="font-semibold text-slate-800">{title}</h3><p className="mt-1 text-sm text-slate-500">{text}</p></div>}
